FROM armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/elastic/filebeat:7.1.1

COPY services/filebeat/filebeat.yml /usr/share/filebeat/filebeat.yml
USER root
# Create a directory to map volume with all docker log files
RUN mkdir /usr/share/filebeat/dockerlogs
RUN chown -R root /usr/share/filebeat/
RUN chmod -R go-w /usr/share/filebeat/
