- name: Setting up the passwordless connection to {{ cluster_id }}
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks: 
   - name: Install pip
     apk: name=py-pip state=present
     
   - name: Install sshpass
     apk: name=sshpass state=present

   - name: Install requests via pip
     pip: name=requests

   - name: Check if MS IP for {{ cluster_id }} is present in hosts file
     shell: grep "\[{{ cluster_id }}_ms1\]" /etc/ansible/hosts | wc -l
     register: ms_hosts_file

   - name: Retrieve and write MS IP for {{ cluster_id }} if not present in hosts file
     shell: python ../files/python-scripts/update_hosts_file_with_vm_ip.py -c {{ cluster_id }} -i ms1
     when: ms_hosts_file.stdout == "0"

   - name: Copy public key to {{ cluster_id }}'s authorized_keys file on MS
     shell: sshpass -p {{ lms_password }} ssh -o UserKnownHostsFile=/dev/null -o CheckHostIP=no -o StrictHostKeyChecking=no root@$(cat /etc/ansible/hosts | grep "\[{{ cluster_id }}_ms1\]" -A 1 | tail -1) "grep -qF -- \"{{ lookup('file', '~/.ssh/id_rsa.pub') }}\" ~/.ssh/authorized_keys || echo \"{{ lookup('file', '~/.ssh/id_rsa.pub') }}\" >> ~/.ssh/authorized_keys"
     when: "'atvts' not in cluster_id"

   - name: Check if WLVM IP for {{ cluster_id }} is present in hosts file
     shell: grep "\[{{ cluster_id }}_wlvm\]" /etc/ansible/hosts | wc -l
     register: wlvm_hosts_file
     when: create_user_on_wlvm

   - name: Retrieve and write WLVM IP for {{ cluster_id }} if not present in hosts file
     shell: python ../files/python-scripts/update_hosts_file_with_vm_ip.py -c {{ cluster_id }} -i wlvm
     when: wlvm_hosts_file.stdout is defined and wlvm_hosts_file.stdout == "0"

   - name: Copy public key to {{ cluster_id }}'s authorized_keys file on WLVM
     shell: sshpass -p {{ wlvm_password }} ssh -o UserKnownHostsFile=/dev/null -o CheckHostIP=no -o StrictHostKeyChecking=no root@$(cat /etc/ansible/hosts | grep "\[{{ cluster_id }}_wlvm\]" -A 1 | tail -1) "grep -qF -- \"{{ lookup('file', '~/.ssh/id_rsa.pub') }}\" ~/.ssh/authorized_keys || echo \"{{ lookup('file', '~/.ssh/id_rsa.pub') }}\" >> ~/.ssh/authorized_keys"
     when: "'atvts' not in cluster_id and create_user_on_wlvm == 'true'"

   - name: Copy public key to {{ cluster_id }}'s authorized_keys file on MS for atvts environments only for testing purpose
     shell: sshpass -p {{ cluster_password }} ssh -o UserKnownHostsFile=/dev/null -o CheckHostIP=no -o StrictHostKeyChecking=no root@$(cat /etc/ansible/hosts | grep "\[{{ cluster_id }}_ms1\]" -A 1 | tail -1) "grep -qF -- \"{{ lookup('file', '~/.ssh/id_rsa.pub') }}\" ~/.ssh/authorized_keys || echo \"{{ lookup('file', '~/.ssh/id_rsa.pub') }}\" >> ~/.ssh/authorized_keys"
     when: "'atvts' in cluster_id"